export const Routes = {
  index: '/',
  onboarding: '/onboarding',
  home: '/home',
  rosary: '/rosary',
  rosaryGuided: '/rosary/guided',
  rosaryCompleted: '/rosary/completed',
  mysteryDetail: (id: string) => `/rosary/mystery/${id}`,
  prayers: '/prayers',
  prayerDetail: (id: string) => `/prayers/${id}`,
  mysteries: '/mysteries',
  mysteryPage: (id: string) => `/mysteries/${id}`,
  kids: '/kids',
  kidsLesson: (id: string) => `/kids/lesson/${id}`,
  kidsShortRosary: '/kids/short-rosary',
  family: '/family',
  paywall: '/premium/paywall',
  settings: '/settings',
  login: '/auth/login',
  register: '/auth/register',
} as const;
